// apps/nemotron/src/components/Faq/Faq.tsx
import { useId, useRef, useState, type KeyboardEvent } from 'react';
import { FAQS } from '../../data/site';
import './Faq.css';

export default function Faq() {
  const uid = useId();
  const [openIndex, setOpenIndex] = useState(0);
  const btnRefs = useRef<(HTMLButtonElement | null)[]>([]);

  const toggle = (i: number) =>
    setOpenIndex((prev) => (prev === i ? -1 : i));

  /* Navegação por setas entre os botões — todos tabáveis (Enter/Space nativos) */
  const onKeyDown = (e: KeyboardEvent<HTMLButtonElement>, i: number) => {
    const last = FAQS.length - 1;
    let next = -1;
    switch (e.key) {
      case 'ArrowDown':
      case 'ArrowRight':
        e.preventDefault();
        next = i === last ? 0 : i + 1;
        break;
      case 'ArrowUp':
      case 'ArrowLeft':
        e.preventDefault();
        next = i === 0 ? last : i - 1;
        break;
      case 'Home':
        e.preventDefault();
        next = 0;
        break;
      case 'End':
        e.preventDefault();
        next = last;
        break;
      default:
        return;
    }
    btnRefs.current[next]?.focus();
  };

  return (
    <section id="faq" className="section faq">
      <div className="container faq-container">
        <header className="faq-head">
          <p className="eyebrow">FAQ · 06</p>
          <h2 className="display faq-title">Perguntas frequentes.</h2>
        </header>

        <div className="faq-list">
          {FAQS.map((item, i) => {
            const open = openIndex === i;
            const headerId = `${uid}-h-${i}`;
            const panelId = `${uid}-p-${i}`;

            return (
              <div className="faq-item" key={item.q}>
                <h3 className="faq-q-title">
                  <button
                    type="button"
                    id={headerId}
                    ref={(el) => {
                      btnRefs.current[i] = el;
                    }}
                    className="faq-btn"
                    aria-expanded={open}
                    aria-controls={panelId}
                    onClick={() => toggle(i)}
                    onKeyDown={(e) => onKeyDown(e, i)}
                  >
                    <span className="faq-q">{item.q}</span>
                    <span
                      className={`faq-icon${open ? ' is-open' : ''}`}
                      aria-hidden="true"
                    >
                      <svg viewBox="0 0 16 16" width="13" height="13" fill="none">
                        <path
                          d="M8 2v12M2 8h12"
                          stroke="currentColor"
                          strokeWidth="1.7"
                          strokeLinecap="round"
                        />
                      </svg>
                    </span>
                  </button>
                </h3>

                <div
                  id={panelId}
                  role="region"
                  aria-labelledby={headerId}
                  aria-hidden={!open}
                  inert={!open}
                  className={`faq-panel${open ? ' is-open' : ''}`}
                >
                  <div className="faq-panel-inner">
                    <p>{item.a}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// apps/qwen-01/src/lib/components/FAQ.svelte
<script lang="ts">
	import { FAQ_ITEMS } from '$lib/data/faq';

	let openIndex = $state<number | null>(null);

	function toggle(index: number) {
		openIndex = openIndex === index ? null : index;
	}

	function onKeydown(e: KeyboardEvent, index: number) {
		switch (e.key) {
			case 'ArrowDown':
				e.preventDefault();
				focusItem(index + 1);
				break;
			case 'ArrowUp':
				e.preventDefault();
				focusItem(index - 1);
				break;
			case 'Home':
				e.preventDefault();
				focusItem(0);
				break;
			case 'End':
				e.preventDefault();
				focusItem(FAQ_ITEMS.length - 1);
				break;
		}
	}

	function focusItem(index: number) {
		const wrapped = ((index % FAQ_ITEMS.length) + FAQ_ITEMS.length) % FAQ_ITEMS.length;
		const buttons = document.querySelectorAll('.faq__trigger');
		(buttons[wrapped] as HTMLElement)?.focus();
	}
</script>

<section class="faq section" id="faq" aria-label="Perguntas frequentes">
	<div class="container faq__container">
		<header class="faq__header">
			<h2 class="heading-section faq__title">Perguntas frequentes</h2>
		</header>

		<div class="faq__list" role="list">
			{#each FAQ_ITEMS as item, i}
				<div class="faq__item" role="listitem">
					<h3>
						<button
							class="faq__trigger"
							aria-expanded={openIndex === i}
							aria-controls="faq-panel-{i}"
							id="faq-trigger-{i}"
							onclick={() => toggle(i)}
							onkeydown={(e) => onKeydown(e, i)}
						>
							<span class="faq__question">{item.question}</span>
							<span class="faq__icon" class:open={openIndex === i} aria-hidden="true">
								<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2">
									<line x1="8" y1="3" x2="8" y2="13" />
									<line x1="3" y1="8" x2="13" y2="8" />
								</svg>
							</span>
						</button>
					</h3>
					<div
						class="faq__panel"
						class:open={openIndex === i}
						id="faq-panel-{i}"
						role="region"
						aria-labelledby="faq-trigger-{i}"
						inert={openIndex !== i}
					>
						<div class="faq__panel-inner">
							<p class="faq__answer">{item.answer}</p>
						</div>
					</div>
				</div>
			{/each}
		</div>
	</div>
</section>

<style>
	.faq__container {
		max-width: 48rem;
	}

	.faq__header {
		text-align: center;
		margin-bottom: var(--sp-12);
	}

	.faq__title {
		font-size: clamp(2rem, 4vw, 3rem);
	}

	.faq__list {
		display: flex;
		flex-direction: column;
		gap: var(--sp-2);
	}

	.faq__item {
		border: 1px solid var(--border);
		border-radius: var(--radius);
		overflow: hidden;
		transition: border-color var(--dur-standard);
	}

	.faq__item:has(.faq__trigger[aria-expanded='true']) {
		border-color: var(--accent-dim);
	}

	.faq__trigger {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--sp-4);
		padding: var(--sp-6);
		text-align: left;
		font-weight: 500;
		font-size: 1rem;
		transition: background-color var(--dur-micro);
	}

	.faq__trigger:hover {
		background: var(--surface);
	}

	.faq__icon {
		flex-shrink: 0;
		width: 16px;
		height: 16px;
		color: var(--accent);
		transition: transform var(--dur-standard) var(--ease-out-back);
	}

	.faq__icon.open {
		transform: rotate(45deg);
	}

	.faq__icon svg {
		width: 100%;
		height: 100%;
	}

	.faq__panel {
		display: grid;
		grid-template-rows: 0fr;
		transition: grid-template-rows var(--dur-dramatic) var(--ease-out-expo);
	}

	.faq__panel.open {
		grid-template-rows: 1fr;
	}

	.faq__panel-inner {
		overflow: hidden;
	}

	.faq__answer {
		padding: 0 var(--sp-6) var(--sp-6);
		color: var(--text-muted);
		font-size: 0.95rem;
		line-height: 1.7;
	}

	@media (prefers-reduced-motion: reduce) {
		.faq__panel {
			transition: none;
		}

		.faq__icon {
			transition: none;
		}
	}
</style>
